name: CI - Maven Build
on:
  push:
    branches: [ main, master]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: "maven"
      - name: Run Checkstyle with inline comments
        uses: dbelyaev/action-checkstyle@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: google_checks.xml
          fail_on_error: true

      - name: Build and Test
        run: mvn -B -DskipTests=false test package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

